{'name': 'ESI - Ocultar Campos y Botones',
 'version': '1.0',
 'category': 'Herramientas extras',
 'summary': 'Compatibilidad histórica ESI; sin modificaciones activas de interfaz',
 'sequence': '10',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'maintainer': 'ESI - Especialistas en Sistemas Integrados',
 'depends': ['sale', 'purchase'],
 'data': [],
 'demo': [],
 'installable': True,
 'application': False,
 'auto_install': False,
 'website': 'https://esibolivia.store'}
