{'name': 'ESI - Tipo de Ventas',
 'version': '13.0.3.1.0',
 'summary': 'ESI - Tipos de venta, flujo configurable, entrega, facturación y pagos desde ventas',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'maintainer': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'category': 'Sales',
 'depends': ['sale_management', 'sale_stock', 'account'],
 'data': ['security/ir.model.access.csv',
          'views/view_main.xml',
          'views/sale_order_inherit.xml',
          'wizard/esi_sale_payment_wizard.xml'],
 'installable': True,
 'application': False,
 'auto_install': False,
 'license': 'LGPL-3'}
