{'name': 'ESI - Tipo de Compras',
 'version': '13.0.1.8.0',
 'summary': 'ESI - Tipos de compra, flujo configurable, recepción, facturación y pagos desde compras',
 'author': 'ESI - Especialistas en Sistemas Integrados',
 'maintainer': 'ESI - Especialistas en Sistemas Integrados',
 'website': 'https://esibolivia.store',
 'category': 'Purchase',
 'depends': ['purchase', 'purchase_stock', 'account'],
 'data': ['security/ir.model.access.csv',
          'views/view_main.xml',
          'views/purchase_order_inherit.xml',
          'wizard/esi_purchase_payment_wizard.xml'],
 'installable': True,
 'application': False,
 'auto_install': False,
 'license': 'LGPL-3'}
